version: "3"

volumes:
  pihole:
  dnsmasq:

networks:
  traefik_default:
    external: true

services:
  pihole:
    image: pihole/pihole
    restart: always
    networks:
      - traefik_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pihole.lolcathost.io`)
      - traefik.http.routers.pihole.tls=true
      - traefik.http.routers.pihole.tls.certresolver=myresolver
      - traefik.http.services.pihole.loadbalancer.server.port=80
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      - DNSSEC=true
      - TZ=Europe/Vienna
      - VIRTUAL_HOST=pihole.lolcathost.io
      - WEBPASSWORD=${WEBPASSWORD}
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d