version: '3'

volumes:
  data:

services:
  reverse-proxy:
    image: traefik
    restart: always
    command:
      - --api.insecure=true 
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.email=tom@sprungknoedl.at
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.myresolver.acme.dnschallenge=true
      - --certificatesresolvers.myresolver.acme.dnschallenge.provider=namecheap
      - --certificatesresolvers.myresolver.acme.dnschallenge.resolvers=9.9.9.9:53,8.8.8.8:53
      - --pilot.token=${TRAEFIK_PILOT_TOKEN}
      - --serversTransport.insecureSkipVerify=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.lolcathost.io`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=myresolver
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    ports:
      - 80:80
      - 443:443
    environment:
      - NAMECHEAP_API_USER=${NAMECHEAP_API_USER}
      - NAMECHEAP_API_KEY=${NAMECHEAP_API_KEY}
      - TRAEFIK_PILOT_TOKEN=${TRAEFIK_PILOT_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/letsencrypt
