version: '3'

volumes:
  data:

networks:
  traefik_default:
    external: true

services:
  portainer:
    image: portainer/portainer-ce
    networks:
      - traefik_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.lolcathost.io`)
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=myresolver
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data